server:
  port: ${PORT:8080}

spring:
  application:
    name: Car Rentals

  datasource:
    url: jdbc:postgresql://ep-wandering-mode-ampnogsw-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_sC5aSHmWJA4M
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  secret: MyCarRentals@Dayanand@1234@secretkey@1
  expiration: 3600000