server:
  port: ${PORT:8080}

spring:
  application:
    name: Car Rentals

  datasource:
    url: ${DB_URL:jdbc:h2:mem:car_rentals;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

logging:
  level:
    org:
      springframework:
        security: ${SECURITY_LOG_LEVEL:INFO}

jwt:
  secret: ${JWT_SECRET:dayanand@car-rentals-organization-mm23451&1}
  expiration: ${JWT_EXPIRATION:3600000}
